package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.Exam;

public interface ExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(Exam record);
}