package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.AccessLog;
import com.kunlunsoft.wxcp.entity.AccessLogWithBLOBs;

public interface TAccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(AccessLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(AccessLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    AccessLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(AccessLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AccessLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(AccessLog record);
}