package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.BaiduAddressReverse;

public interface TBaiduAddressReverseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(BaiduAddressReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(BaiduAddressReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    BaiduAddressReverse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(BaiduAddressReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baidu_Address_reverse
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(BaiduAddressReverse record);
}