package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.TCompressFailedPic;

public interface TCompressFailedPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(TCompressFailedPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(TCompressFailedPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    TCompressFailedPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(TCompressFailedPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_compress_failed_pic
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(TCompressFailedPic record);
}