package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.Convention;

public interface TConventionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(Convention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(Convention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    Convention selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(Convention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Convention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(Convention record);
}