package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.Girl;

public interface TGirlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    Girl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_girl
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(Girl record);
}