package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.ImgItem;

public interface TImgItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(ImgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(ImgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    ImgItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(ImgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(ImgItem record);
}