package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.MidTestConvention;

public interface TMidTestConventionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mid_test_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(MidTestConvention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mid_test_convention
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(MidTestConvention record);
}