package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.ProductBaseInfo;

public interface TProductBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(ProductBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(ProductBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    ProductBaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(ProductBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_base_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(ProductBaseInfo record);
}