package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.ShareItem;

public interface TShareItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(ShareItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(ShareItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    ShareItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(ShareItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(ShareItem record);
}