package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.SimpleInfo;

public interface TSimpleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(SimpleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(SimpleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    SimpleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(SimpleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SimpleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_simple_info
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(SimpleInfo record);
}