package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.TimingTaskItem;

public interface TTimingTaskItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(TimingTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(TimingTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    TimingTaskItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(TimingTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timing_task_item
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(TimingTaskItem record);
}