package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.TVoteLog;

public interface TVoteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insert(TVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int insertSelective(TVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    TVoteLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(TVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Fri Sep 28 12:46:52 CST 2018
     */
    int updateByPrimaryKey(TVoteLog record);
}