package com.kunlunsoft.wxcp.mapper;

import com.kunlunsoft.wxcp.entity.WxCpCommandToSuite;

import java.util.List;

public interface WxCpCommandToSuiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_cp_demo..wx_cp_command_to_suite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_cp_demo..wx_cp_command_to_suite
     *
     * @mbg.generated
     */
    int insert(WxCpCommandToSuite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_cp_demo..wx_cp_command_to_suite
     *
     * @mbg.generated
     */
    WxCpCommandToSuite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_cp_demo..wx_cp_command_to_suite
     *
     * @mbg.generated
     */
    List<WxCpCommandToSuite> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_cp_demo..wx_cp_command_to_suite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxCpCommandToSuite record);
}